stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o myapp

package:
  stage: package
  image: ubuntu:latest
  dependencies:
    - build
  artifacts:
    paths:
      - app
  script:
    - tar -czf myapp.tar.gz app

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh 
    - chmod 400 $id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - scp -r -i $id_rsa app.tar.gz $EC2_USER@$EC2_HOST:/home/$EC2_USER/
    - ssh -i $id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'tar -xzf /home/$EC2_USER/app.tar.gz -C /home/$EC2_USER/ && nohup /home/$EC2_USER/app > /dev/null 2>&1 &'
