stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app.exe

package:
  stage: package
  image: mcr.microsoft.com/windows:ltsc2019
  dependencies:
    - build
  artifacts:
    paths:
      - app.exe
  script:
    - 7z a app.zip app.exe

deploy:
  stage: deploy
  image: mcr.microsoft.com/windows:ltsc2019
  before_script:
    - choco install openssh
    - echo "$SSH_PRIVATE_KEY" > id_rsa
  script:
    - scp -i id_rsa -o StrictHostKeyChecking=no app.zip $EC2_USER@$EC2_HOST:/home/$EC2_USER/
    - ssh -i id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'unzip /home/$EC2_USER/app.zip -d /home/$EC2_USER/ && nohup /home/$EC2_USER/app.exe > /dev/null 2>&1 &'
