stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o myapp

package:
  stage: package
  image: ubuntu:latest
  dependencies:
    - build
  artifacts:
    paths:
      - app
  script:
    - tar -czf myapp.tar.gz app

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" > id_rsa
  script:
    - scp -i id_rsa -o StrictHostKeyChecking=no app.tar.gz $EC2_USER@$EC2_HOST:/home/$EC2_USER/
    - ssh -i id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'tar -xzf /home/$EC2_USER/app.tar.gz -C /home/$EC2_USER/ && nohup /home/$EC2_USER/app > /dev/null 2>&1 &'
