stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o myapp
    - ls -l

package:
  stage: package
  image: alpine:latest
  before_script:
    - apk add zip
  script:
    - mv myapp /tmp/myapp
    - cd /tmp
    - zip myapp.zip myapp
  artifacts:
    paths:
      - /tmp/myapp.zip

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
    - chmod 600 id_rsa
    - mkdir -p ~/.ssh && mv id_rsa ~/.ssh/id_rsa
    - echo -e "Host $EC2_HOST\n\tStrictHostKeyChecking no\n\tUser $EC2_USER\n\n" >> ~/.ssh/config
  script:
    - scp app.zip $EC2_USER@$EC2_HOST:/home/$EC2_USER/
    - ssh $EC2_USER@$EC2_HOST 'unzip myapp.zip && chmod +x app && ./app'
